# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getgitignore < Formula
  desc "Tool to get Git Ignore files from GitHub GitIgnore"
  homepage "https://github.com/joeds13/getgitignore"
  version "0.0.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joeds13/getgitignore/releases/download/0.0.1/getgitignore_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "4c45e05be3cae2568732da11f7c16c254e2b571a4e84b6c1c695c9788fd54e2d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/joeds13/getgitignore/releases/download/0.0.1/getgitignore_0.0.1_Darwin_arm64.tar.gz"
      sha256 "1ad54bff1683c2e3723b29ba5d0f997b10c9ced542ffc6c179dff53b5651b4e7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joeds13/getgitignore/releases/download/0.0.1/getgitignore_0.0.1_Linux_x86_64.tar.gz"
      sha256 "61af2a6f2c8b49d1a80b0681a00b32c7075e230769211b21f02cf9f084ef0e5f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeds13/getgitignore/releases/download/0.0.1/getgitignore_0.0.1_Linux_arm64.tar.gz"
      sha256 "1a3999ca925e17d58e3a4b94ffcef7233cf947abc2fc6d84fb16e45e5dbc25bf"
    end
  end

  def install
    bin.install "getgitignore"
  end

  test do
    system "#{bin}/getgitignore version"
  end
end
